#
server:
  port: 7000
#
logging:
  config: classpath:logback.xml
#####################
#（★）Spring
#####################
spring:
  application:
    name: study-springboot-mvc
  main:
    banner-mode: 'off'
    web-application-type: servlet
  profiles:
    active: @env@
  #====================
  #（▲）文件上传
  #====================
  servlet:
    multipart:
      enabled: true
      #单文件大小
      max-file-size: 100MB
      #总文件大小
      max-request-size: 10MB
  #====================
  #（▲）
  #====================
  thymeleaf:
    prefix: classpath:/templates
    suffix: html
    cache: false
    mode: HTML