#
server:
  port: 7000
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springboot-shiro-web
  main:
    web-application-type: servlet
    banner-mode: 'off'
  profiles:
    active: @env@
  #====================
  #（▲）
  #====================
  thymeleaf:
    prefix: classpath:/templates
    suffix: html
    cache: false
    mode: HTML